### ISSUE TITLE
Please increase the time to .GetCurrentDocumentElement().

### ISSUE THREAD

**Issue by LAPIII** [Descolada/UIA-v2#14]
On days when I have extremely slow internet, it seems to take half a minute to visit a website and so I usually get an error.

EDIT: Also I'd like `if button` / `else`  or `try` / `catch` to be better. This would be useful to check if sites are logged into.  

EDIT: Is it possible to get a handle for `Settings`? I tried `Settings ahk_exe ApplicationFrameHost.exe` and, the process listed @ Task manager for Windows 11, `Settings ahk_exe SystemSettings.exe`.

**Comment by Descolada** [comment]
One key part of `UIA_Browser` initialization is getting the Reload buttons current name and considering that state as being "Reload". This is because determining whether a page has loaded in multiple browsers with multiple possible languages is very tricky, and UIA_Browser does it by checking the reload button name: if it is named "Reload" then the page has loaded, if it is "Stop" then the page is still loading. For example in English the reload button in Chrome can be named "Reload this page" or "Stop", whereas if the computer is set to other languages then those will be different: this is why I can't simply check whether the button name is "Reload"/"Stop"/"Refresh" etc. 
This means that for UIA_Browser to work properly, the page HAS to be loaded before calling `UIA_Browser(WinTitle)`. If you have slow internet then you can use `Run "chrome.exe"` to open the New Tab page which loads very quickly and usually after that `WinWaitActive "ahk_exe chrome.exe"` with a small Sleep is enough. Then you can use `cUIA.Navigate()` to go to the new page and it will wait for it to load indefinitely. Alternatively use `UIA.ElementFromHandle("ahk_exe chrome.exe").WaitElement({Name:"Some known element"})` to wait for a known element to exist on the page which would usually mean the page has loaded, OR set a long enough Sleep to wait for a complete load (eg 30 seconds). 

I don't know what you mean by `if button` / `else` to "be better". Currently there are `cUIA.ElementExist({condition})` and `cUIA.ElementFromPathExist("path")` that can be used in if...else and I don't know how to make them even simpler.

In Windows 10 I could get the element for `Settings` just fine: `MsgBox UIA.ElementFromHandle("Settings ahk_exe ApplicationFrameHost.exe").DumpAll()`. Don't know about Windows 11, perhaps try running with UIAccess or as admin?
