### ISSUE TITLE
UIA Browser won't work with Perplexity.ai.

### ISSUE THREAD

**Issue by LAPIII** [Descolada/UIA-v2#15]
I've tried using both edge and chrome. Below is my chrome script as well as error:

```
#SingleInstance Force
#Requires Autohotkey v2.0+
#Include <UIA>
#Include <UIA_Browser>
Run "chrome.exe https://www.perplexity.ai/"
cUIA := UIA_Browser()
cUIA.ElementFromHandle("ahk_exe chrome.exe")

cUIA.WaitElementFromPath("VR0q").Click() ; Login
```

[TEST-ahk-30-09-23-09-12-01-978-AM.jpg](https://postimg.cc/tY6kXkRz)

**Comment by Descolada** [comment]
Hello,
As with any other AHK function, if a WinTitle is not provided then the Last Known Window is used. In your example there is no last known window, because `Run` function doesn't set one. Thus you can fix the error by using `cUIA := UIA_Browser("A")`, or using a `WinWaitActive` before it as the examples do. For example,
```
Run "chrome.exe https://www.perplexity.ai/"
WinWaitActive "ahk_exe chrome.exe"
Sleep 500
; Initialize UIA_Browser, use Last Found Window (returned by WinWaitActive)
cUIA := UIA_Browser()
```
The WinWaitActive and Sleep also make sure that the window has opened properly, but if you are opening a site directly then I recommend adding a longer Sleep to make sure the page has loaded correctly (otherwise UIA_Browser will not work properly!). Alternatively wait for a element with a known name to exist before calling UIA_Browser, for example:
```
Run "chrome.exe https://www.perplexity.ai/"
WinWaitActive "ahk_exe chrome.exe"
UIA.ElementFromHandle().WaitElement({Name:"Login"})
Sleep 200 ; Small sleep to make sure the Reload button has changed to "Refresh"
cUIA := UIA_Browser()
```

By the way, here
```
cUIA := UIA_Browser()
cUIA.ElementFromHandle("ahk_exe chrome.exe")
```
the `cUIA.ElementFromHandle("ahk_exe chrome.exe")` does nothing so you can remove it (you aren't storing the result in a variable, so the result is destroyed immediately).
