### ISSUE TITLE
Using condition in tree walker gets the wrong element

### ISSUE THREAD

**Issue by enaaab460** [Descolada/UIA-v2#2]
![image](https://user-images.githubusercontent.com/34572749/221437706-109a434b-cd24-4c97-9eca-37835fb1612d.png)
I am trying to get the text element "CARDIOLOGY CHAPTER" from link element "Lec 2 Angina Pectoris" using treewalker. When using `linkUiaElement.WalkTree("-1",{T:20})` i get the "1. Lec 1 Introduction" text element, which is not the expected behaviour. If I understand correctly, this is not a sibling, it is a nephew (xd). I would reach this element using the path "-1,3"
When using `linkUiaElement.WalkTree("-1")` i get the "  1. Lec 1 Introduction" link element, which is the expected behaviour since it is the previous sibling, but I want to use the filter condition to choose the Last text sibling element previous to the pointed link element.

Is there a problem in my code or is this a bug?
I understand that in this very example, i can use `linkUiaElement.WalkTree("-2")`, but this list is long complex with different patterns of link and text elements that I need to dynamically figure out the last text sibling for a group of link elements

**Comment by Descolada** [comment]
Hello,
This is the expected behavior when using a TreeWalker with a filter-condition, because the tree gets "flattened" when using a condition. So even though `• • 1. Lec 1 Introduction` Text element is a child of a Link element, after flattening the tree it will be on the same level as your target Text element and will get selected instead. 

I see two possible ways of tackling this problem:
1) Loop `linkUiaElement.WalkTree("-1")` until you find a Text-type element
2) Use `FindElement` from the parent of the "Angina Pectoris" element, with TreeScope Children and startingElement "Angina Pectoris": `AnginaPectorisParent.FindElement({Type:"Text", i:-1, startingElement:AnginaPectorisLinkElement, scope:"Children"})`

**Comment by enaaab460** [comment]
The loop way works
the findelemnt way matches the "Lec 2 Angina Pectoris" text element (the very last item in the screenshot, and the last child of the "Lec 2 Angina Pectoris" link element)

**Comment by Descolada** [comment]
The FindElement way should work as well, but make sure you are calling it on the parent of the element that is selected in the screenshot. If you are do that and using TreeScope Children, then it's not possible to match "Lec 2 Angina Pectoris" Text element.

**Comment by enaaab460** [comment]
![image](https://user-images.githubusercontent.com/34572749/221781969-1bccd5fc-964f-4343-b945-effe52d717eb.png)

**Comment by Descolada** [comment]
Interesting, I will look into it. Is there any way for me to access that program for testing purposes?

**Comment by enaaab460** [comment]
It is my college's online lectures' app, with tight lockdown on sign in access :(

**Comment by Descolada** [comment]
Okay. I'll try to find something similar on the web, but if you find an example first, please share it here.

**Comment by enaaab460** [comment]
I tried replicating the script on your script's [wiki](https://github.com/Descolada/UIA-v2/wiki/02.-UIA-tree) and it works as expected:

`WinActivate "Chrome"
program := UIA.ElementFromWindow("Chrome")
listElementParent := program.ElementFromPath({ T: 30 }, { T: 26, A: "js-repo-pjax-container" }, { T: 26, A: "wiki-pages-box" })
listElementParent.Highlight(1000)
listElement := listElementParent.ElementFromPath({ T: 8 })
listElement.Highlight(1000)
targetLast := listElementParent.FindElement({ Type: 20, i: -1, startingElement: listElement, scope: "Children" })
targetLast.Highlight`

https://user-images.githubusercontent.com/34572749/221808379-a5304ac0-73bb-4711-9b2c-a77ceaebd3da.mp4

![image](https://user-images.githubusercontent.com/34572749/221808763-9f8355d2-97d9-4720-b78f-dd6146050fc3.png)
the selected list is the list element
I am not sure if this is equivalent to my first scenario

**Comment by enaaab460** [comment]
New Update:
I think the problem might be the tree itself
I tried linkElement.Walktree("P1") and the parent I am getting is a group, even though the tree shows the parent as a document
![image](https://user-images.githubusercontent.com/34572749/221854077-e90a0ad8-cb2a-4d40-8fd3-f1ba75f2f51b.png)

**Comment by enaaab460** [comment]
Looks like the looping method will be the right way to do this
Thanks alot for your help!!!

**Comment by Descolada** [comment]
The issue appears to be instead with the internally used method [FindFirstWithOptions](https://learn.microsoft.com/en-us/windows/win32/api/uiautomationclient/nf-uiautomationclient-iuiautomationelement7-findfirstwithoptions), which is very sparsely documented. I had assumed that when using the `root` argument, the search scope would be applied in relation to the `root` and the first validated element would be the element the method was called from. Instead the search scope is `scope` for the element it's called from, but TreeScope Descendants for the `root` element. Whether this should be the expected behavior or a bug on Microsofts part, I am not yet sure and will be submitting some queries to Microsofts Q&A. I'll be keeping this issue open until I get a response from there.
