### ISSUE TITLE
Select A color point and control the saturation.

### ISSUE THREAD

**Issue by 12Arthor** [Descolada/UIA-v2#25]
Hi, and happy new year first.

I don't understand something.
Two weeks ago my script working and now it doesn't work anymore.

I create a script for Davinci resolve to control Hue vs Sat curves with my streamdeck.
The script select the blue dot and after it select the value of "Saturation" and clik on it and stay hold, so that i can control the slide with my my streamdeck button.

This the code that worked two weeks ago.

#include UIA.ahk

ResolveEl := UIA.ElementFromHandle("DaVinci Resolve Studio ahk_exe Resolve.exe")
ResolveEl.ElementFromPath("RQRRQ/Q/Q/QqRQQQRRQ/RRQ/Q0t").Invoke()
ResolveEl := UIA.ElementFromHandle("DaVinci Resolve Studio ahk_exe Resolve.exe")
ResolveEl.ElementFromPath("RQRRQ/Q/Q/QqRQQQRRQ/RRQ/Q/Q/K").Click("Down")

and now when a launch it the blue is invoke but the control of my saturation brings my mouse to the very bottom of my screen.

How can i bring my mouse on a text tool and click and hol my mouse on it with elementfrompath if it's possible ?

Thank you very much.

I attached a screen of the tool a need to control.
![2024-01-06_16h43_47](https://github.com/Descolada/UIA-v2/assets/113166860/5496cbe4-c1cb-4bf6-9f75-ac88b1e2eabe)

**Comment by Descolada** [comment]
Hello,
ElementFromPath can change if the user interface of the program changes enough, such as if you were to open/close enough widgets in DaVinci, or perhaps with an update. This is also ElementFromPath doesn't work well in browsers, because websites often change. For example in my setup the path that worked was instead `ResolveEl.ElementFromPath("RQRRQ/Q/Q/QRQQQRRQ/RRQ/Q0t").Invoke()`.

A better, perhaps more reliable method is to use FindElement instead, which is much more resistant to user interface changes. This selected the blue color and then pressed down on the Saturation tool:
```
ResolveEl.FindElement({ClassName:"UiSecHueSatCurveWidget"}).FindElement({Type:"Button", i:5}).Invoke()
ResolveEl.FindElement({Name:"Saturation", Type:"Text"}).WalkTree("+1", {Type:"Text"}).Click("Left",, "Down")
```

By the way, you don't need to use `ResolveEl := UIA.ElementFromHandle("DaVinci Resolve Studio ahk_exe Resolve.exe")` multiple times, just once is enough (unless you close the window between selecting the blue color and pressing on Saturation...).

**Comment by 12Arthor** [comment]
Thank you,

I have some questions.
Where did you find in UIA "UiSecHueSatCurveWidget" ?

I just copy and past your code and it's the same issue for me my mouse goes on the down of my screen and doesn't click and hold down. I don't understand why.

Thank you for your patience

**Comment by 12Arthor** [comment]
When i use the Hightlight command the tool it's highlighted but when i go in the click command my mouse goes on the very bottom of my screen

![image](https://github.com/Descolada/UIA-v2/assets/113166860/5036fe9f-1f72-4ebc-93d0-069f466e72e4)

**Comment by Descolada** [comment]
Quite weird. Are you perhaps using a multiple monitor setup with different screen scalings? That is the only case I can think of that could cause such a problem, and it can be fixed by adding `DllCall("SetThreadDpiAwarenessContext", "ptr", -3, "ptr")` to the top of your code, or alternatively `UIA.SetMaximumDPIAwareness()`.

**Comment by 12Arthor** [comment]
Yes i have 3 monitors

Monitor 1 : in the middle UHD
Monitor 3 : on the Left FHD
Monitor 2 : on the Right FHD

**Comment by 12Arthor** [comment]
I add DllCall("SetThreadDpiAwarenessContext", "ptr", -3, "ptr") on the top  of my code and it's working. I love you you are the best Thank you somuch <3
