### ISSUE TITLE
Support to LostFocus

### ISSUE THREAD

**Issue by apollo8388** [Descolada/UIA-v2#31]
Hello there!
i need to know when a windows lost focus, and it could be done with workaround, but would be great to implement it!

By the way, awsome work!
its being VERY usefull!
Congrats!

**Comment by Descolada** [comment]
You don't need to use UIA for that. I recommend using SetWinEventHook with EVENT_OBJECT_FOCUS to detect focus change events, and keep track of the active window - if it changes then you know the window lost focus. An example of SetWinEventHook is available [here](https://www.autohotkey.com/boards/viewtopic.php?f=96&t=120588).

**Comment by apollo8388** [comment]
Thanks a lot! ill test it!
by the way, why not using uia for that?

**Comment by Descolada** [comment]
You can use UIA for that, but generally it's slower because UIA also provides the sending element, and getting it requires cross-process communication. So if you don't need the sending element then use SetWinEventHook instead. I also wrote a wrapper for it: [WinEvent library](https://www.autohotkey.com/boards/viewtopic.php?f=83&t=126932), with which you could use `WinEvent.NotActive(Calllback)`.
