### ISSUE TITLE
I can't see UIAViewr.

### ISSUE THREAD

**Issue by LAPIII** [Descolada/UIA-v2#34]
It won't show up. I had restarted and re-copied the library from the repository. I had noticed that UIAViewr wasn't remembering position with the option enabled and saved.

EDIT: I also checked if UIA Browser was up to date so I recopied and, when ran, got:

[![UIA-Browser-ahk-16-03-24-03-00-21-491-PM.jpg](https://i.postimg.cc/k4qBQdH3/UIA-Browser-ahk-16-03-24-03-00-21-491-PM.jpg)](https://postimg.cc/06Xkvhxc)

**Comment by Descolada** [comment]
I'm not sure what could be going wrong. My first suggestion is to recopy UIA.ahk from GitHub. If you are copy-pasting it in text form, make sure to copy it from the raw code page [available here](https://raw.githubusercontent.com/Descolada/UIA-v2/main/Lib/UIA.ahk), otherwise there might be weird formatting issues. If that doesn't fix it, try to delete the config file in your AppData folder (userfolder\AppData\Roaming\UIAViewer\settings.ini).

**Comment by LAPIII** [comment]
It did work to delete settings.ini, thank you.
