### ISSUE TITLE
UIA - conditional path - not getting the boundary rectangle 

### ISSUE THREAD

**Issue by henriqueterada** [Descolada/UIA-v2#6]
Hello Descolada,
Thanks for the fix this past week.
I just tested, and made a video here with the output of what is going on.
I hope this helps.
Thanks
Henrique
https://youtu.be/tpYFWJZgnd0

**Comment by Descolada** [comment]
Hello,
I don't think this is actually an UIA problem, but rather how you are assigning the condition path to your `button3` variable. 

Take this line:
```
buttonlocation3 := { T: 33, CN: "TPanel", i: -1}, { T: 33, CN: "TGradientPanel" }, { T: 33, CN: "TGradientPanel" }, { T: 33, CN: "TGradientPanel", i: -1 }
```
AHK will interpret this as follows:
```
buttonlocation3 := { T: 33, CN: "TPanel", i: -1} ; create object, assign to variable "buttonlocation3"
{ T: 33, CN: "TGradientPanel" } ; create and discard object
{ T: 33, CN: "TGradientPanel" } ; create and discard object
{ T: 33, CN: "TGradientPanel", i: -1 } ; create and discard object
```

If you want to assign it to a variable, you will need to use array expansion for that:
```
buttonlocation3 := [ { T: 33, CN: "TPanel", i: -1}, { T: 33, CN: "TGradientPanel" }, { T: 33, CN: "TGradientPanel" }, { T: 33, CN: "TGradientPanel", i: -1 } ]
; some other code
el.ElementFromPath(buttonlocation3*)
```
Here we first create an array containing the path, and then use `buttonlocation3*` to expand that array to `el.ElementFromPath({ T: 33, CN: "TPanel", i: -1}, { T: 33, CN: "TGradientPanel" }, { T: 33, CN: "TGradientPanel" }, { T: 33, CN: "TGradientPanel", i: -1 })`

The other way is not to use a variable, but use the path directly in the ElementFromPath call.

UIA path doesn't have this problem, because it's a string.

I hope this fixes your problem!

**Comment by henriqueterada** [comment]
Thanks a lot, let me try and I'll get back to you later

HT
