### ISSUE TITLE
Can i hide element or control from some window?

### ISSUE THREAD

**Issue by hsayed21** [Descolada/UIA-v2#7]
in windows that have controls support ClassNN
easy use this to hide a specific control from window
```ahk
Control, Hide,,TrayInputIndicatorWClass1, ahk_class Shell_TrayWnd 
```

but some windows not have ClassNN for its controls
So, I thinking this UIA-v2 is awesome to get control from what ever with multi attribute instead of ClassNN
we can benefit from that to hide some controls.

This is my question.

**Comment by Descolada** [comment]
I refer to [this StackOverflow answer](https://stackoverflow.com/questions/10421377/how-to-move-an-ui-automation-element-to-a-different-location). Short answer: it usually isn't possible, because UIAutomation is designed to manipulate content as a regular user would, and hiding elements isn't usually part of that.

If dealing with an older window (that has ClassNN anyway for controls), then you can get the handle to that control with `Element.GetControlId()` and then call `WinHide` on that handle to hide it. This won't work for example in Chromium windows, because all content is rendered on the screen as a webpage, and the control for all webpage elements is the renderer control. Hiding that will simply hide all the content.
